### PR TITLE
Refactored homepage / small modifications to feed css

### PR DESCRIPTION
**Pull request by crabdul**

### CODE REVIEW

**Comment by crabdul** [comment]
Is the website split into appropriate apps?

Also, with regards to the base template files like head, nav etc, should they belong to templates in a separate folder in the root directory (e.g a folder called 'common-static/layouts'? 

At the moment, they are inside the hackfeed (former blog) app template folder and I don't think they should belong there

**Comment by harjeetkalsi** [comment]
I agree that its important to separate the apps, and that the apps blog, mapToBreathe and Subscribe you be seperate apps. Not sure 'Events' should be separate app from 'Blog' as they might need to share the same database. I think for now restructuring is not too important, as we can do it in a month after a bit more development as it might be clearer then to see how things are connected? So for now having 'blog', 'mapToBreathe' and 'Subscribe' as the separate app, then when things get on a bit more we know what to separate as we'll know clearer what things aren't connected? what do you think @Bishwin and @MaxAwan

**Comment by alectronic0** [comment]
screenshot from 2018-02-25 12-54-28

got this going  to http://localhost:8000/hackfeed/

also had issuie looking at the admin page


other than that look pretty :)

**Comment by alectronic0** [comment]
Also you need to ignore the root `/static` file or rename to `staticfile` due to it being generated stuff
@MaxAwan & @Bishwin what best practices on this

**Comment by Bishwin** [comment]
I agree with harjeet.   
Its great you're thinking longterm, but currently there isn't much need in separating these apps until we have a concrete MVP and a need to move them. It could cause unwanted complexity as this early stage. Once we have a stable site that's functional then we can start to optimise and improve.

**Comment by crabdul** [comment]
@alectronic0 the blog app is now called hackfeed so you need to create new tables

**Pull request closed without merging**
