### PR TITLE
css refactored for feed, about, events. navbar changes. npm material.io package added

### PR DESCRIPTION
**Pull request by crabdul**

### CODE REVIEW

**Comment by crabdul** [comment]
I commited .DS_Store files and one blog migration file by mistake and pushed them to remote. In my next commit I removed them. Is this ok to do? 
I didn't want to mess with the remote history. 
But since I'm the only person working on this branch, could I possibly reset the last two commits locally and force push to my remote?
`
# reset to previous commit (not sure what the command for last two is. maybe twice?)
git reset HEAD^ --hard
git push origin/css-refactoring -f
`

What are your suggestions?

**Comment by alectronic0** [comment]
why is have you installed npm??? this a django project not a node project???

**Comment by crabdul** [comment]
I want to use gulp to compile SCSS.
But I'll remove it

**Comment by Stivaros** [comment]
To answer your question, @crabdul, the best way to have done this would be `git revert <commit you want to undo>`. It preserves the history of the branch. If you're just working locally use `git reset HEAD~2`, where 2 is two commits off head but could be any number.

@alectronic0 play nice and stop scaring people.

**Comment by crabdul** [comment]
@Stivaros cheers for your answer. I'll use that next time. Because I already pushed to my remote, I used 
```
git reset HEAD^ --hard
// force push
git push origin -f
```

**Comment by Stivaros** [comment]
Yeah, it basically reverses the changes made within a commit and makes a new commit which says "Revert...", so it's perfect for remote reverses as it provides a transparent history.

You want to avoid force pushing for situations like that because there's no transparency, suddenly the HEAD moves. No harm though as you were the only one working on this branch.

**Pull request closed without merging**
